### ISSUE TITLE
[BUG] LaTeX Prefix and Suffix not correct and not picked up by Anki/PDFTeX

### ISSUE THREAD

**Issue by andrewcrook** [alemayhu/notion2anki#1]
/latex or /math blocks are imported however the prefix and suffix of the LaTeX string isn't picked up by Anki.

**Example  in Notion**
<img width="448" alt="image" src="https://user-images.githubusercontent.com/803618/80865550-2570ad80-8c82-11ea-94d1-4eacf53340eb.png">

**Result in Anki**
<img width="235" alt="image" src="https://user-images.githubusercontent.com/803618/80865524-f5290f00-8c81-11ea-8506-8e6f27ecd04d.png">

**Expected (one of the following)**
 **_i.e requiring the square brackets and the closing forward slash._**

<img width="252" alt="image" src="https://user-images.githubusercontent.com/803618/80865682-e0994680-8c82-11ea-8cfd-57ef5b0e1336.png">

**Comment by scanf** [comment]
Hei again, appreciate you taking the time to report this. I have added a minor workaround that is very fragile and will only work for simple cases. 

Your bug report made me eyeball the Anki manual and it's obvious there is a lot of stuff there I don't know about. I will try read up today and make the tool behave more "correct" with regards to the descriptions in the manual. It will probably take me a couple of days. If you see any other issues, please reopen issues or create new ones. 

Thanks.

**Comment by andrewcrook** [comment]
@scanf   Thanks, because Notion doesn’t support inline equations they will be on their own line. If you are reading line by line,  I think all that is needed is to test the line for starting with $$ and ending with $$ and just replace the first with [$$] and the latter with [/$$]. I cannot think of any clashes that might arise. I will test when I can.

**Comment by scanf** [comment]
@andrewcrook were your issues ever solved? I have made some changes since and also added support for using the exported HTML output now. I would love to get your feedback and bugs if any 😄 

Thanks.
