### ISSUE TITLE
Generate pages from the YouTube playlists / videos

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#110]
Would be good to have some pages with all of the videos.

**Comment by scanf** [comment]
We could even put them all under the useful links section. Like a huge wall of videos using `youtube-embed inline=true`.

**Comment by aalemayhu** [comment]
While this would be nice to have, it's kind of out of scope. I will probably make different tool specifically for this purpose.

**Comment by aalemayhu** [comment]
Reopening — never implemented (closed without a linked PR). Maps to the audio/video → cards moonshot bet (D in the trio synthesis on #2506). Engineer's quarter sequence: E (#2506) → D (this) → G.

**Comment by aalemayhu** [comment]
Closing this as housekeeping — these tutorial-video tasks have been open since 2020 and haven't aged into actionable code work. If a specific feature would help new users learn the flow, open a focused issue with the workflow you'd want documented.
