### ISSUE TITLE
webp images do not work with Anki

### ISSUE THREAD

**Issue by scanf** [alemayhu/notion2anki#15]
Looks like they are treated as links. I suspect this has to be fixed upstream.

**Comment by scanf** [comment]
works fine with newer Anki versions, maybe it was an export glitch earlier?

**Comment by LuGHuaaa** [comment]
Images cannot be displayed on multi-level sub-pages. it is a Problem?

example: https://www.notion.so/tyes5812/page-77fd11ba5c084651a126ace8e15fba51

**Comment by aalemayhu** [comment]
Not sure if this is related to this issue, but I will take a look. 

Thanks for including an example, saves me time!
- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitch: http://twitch.tv/alexanderalemayhu <http://twitch.tv/alemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
More Links: https://links.alemayhu.com <https://links.alemayhu.com/>

**Comment by aalemayhu** [comment]
@LuGHuaaa should be fixed soon, can you confirm it works as expected?

**Comment by LuGHuaaa** [comment]
@aalemayhu It works, thank you.
