### ISSUE TITLE
deck background not working?

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#154]
Had some issues while doing a regression test while reviewing #152. Looks like it also happens in production. Probably something that broke recently.

https://github.com/alemayhu/notion2anki/pull/152

**Comment by alpkaanaksu** [comment]
It is working for me.

<img width="608" alt="2020-09-12 21_27_54-notion2anki - Anki" src="https://user-images.githubusercontent.com/68744864/93002333-f414c200-f53e-11ea-8c1e-087caefb5dea.png">

**Comment by aalemayhu** [comment]
This is not affecting everybody, just me. So deffered for next week.

**Comment by aalemayhu** [comment]
Something weird must be happening with my setup.

I have not used my Android device for a while. I wonder how it looks like there 🤔

Moving this to next week.

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: https://www.youtube.com/channel/UCVuQ9KPLbb3bfhm-ZYsq-bQ
Twitter: https://twitter.com/aalemayhu
Twitch: http://twitch.tv/alemayhu

**Comment by aalemayhu** [comment]
I think the problem is due to me using custom options group. Maybe even a bug in Anki. Either way it's not bugging me enough to warrant an investigation just yet. Moving into a future milestone.

**Comment by guillem-palau-salva** [comment]
Have you tried to start Anki without add-ons? Perhaps you have some add-on that is overriding something or generating conflicts due to monkey patching

**Comment by aalemayhu** [comment]
Yeah, you are right. This seems to be working fine when all add-ons are disabled on my side. No idea what is actually causing it.
