### ISSUE TITLE
Input doesn't work if there is nothing inside of the toggle

### ISSUE THREAD

**Issue by alpkaanaksu** [alemayhu/notion2anki#158]
### This works:
![image](https://user-images.githubusercontent.com/68744864/93334878-46e7c580-f82e-11ea-9465-38a04ac505f9.png)

### This doesn't
![image](https://user-images.githubusercontent.com/68744864/93334923-58c96880-f82e-11ea-9a04-223ab5e83da5.png)

![image](https://user-images.githubusercontent.com/68744864/93334956-64b52a80-f82e-11ea-8004-114a0946bbc8.png)

**Comment by aalemayhu** [comment]
I forgot about this issue, will fix it next week unless someone else beats me to it 😉

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: https://www.youtube.com/channel/UCVuQ9KPLbb3bfhm-ZYsq-bQ
Twitter: https://twitter.com/aalemayhu
Twitch: http://twitch.tv/alemayhu

**Comment by aalemayhu** [comment]
Fixed on the dev branch
