### ISSUE TITLE
Update the thumbnail of the video we see on the homepage

### ISSUE THREAD

**Issue by alpkaanaksu** [alemayhu/notion2anki#164]
Ideally, we will decide on colors/fonts before we do that. We can make it look integrated and in harmony with the rest of the website.

This is what I mean:
<img width="885" alt="2020-09-22 21_23_19-Free Website for Notion to Anki Conversion" src="https://user-images.githubusercontent.com/68744864/93922116-2fbb4300-fd1a-11ea-8bc2-c46cf5034a9d.png">

**Comment by aalemayhu** [comment]
The front page has since changed. I am still open for the colour changes but those can be addressed in individual issues.
