### ISSUE TITLE
card styles are not stable

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#166]
Things change too much across versions.

**Comment by aalemayhu** [comment]
We can resolve this by freezing the default card templates.

**Comment by guillem-palau-salva** [comment]
Just to suggest to name future edits by version i.e. notion2anki-inoutCardv02 etc. A quick tutorial can be published about how to update notes with prior versions of the template. It's just a matter of seconds.  This way, you avoid having many different note types with 5 random hex characters.

**Comment by aalemayhu** [comment]
This has been resolved since we will be freezing the note types moving forward.
