### ISSUE TITLE
Create video showing how to change toggle behaviour in Anki

### ISSUE THREAD

**Issue by alpkaanaksu** [alemayhu/notion2anki#175]
> I exported a lot of cards with the 'open nested toggles' feature on. I think I like it better without this. Is there a way to reverse this on Anki?

StrikerForce1000 on Discord

**Comment by alpkaanaksu** [comment]
I'll do this tomorrow.

**Comment by alpkaanaksu** [comment]
There is currently a problem with Anki. I'll do the video as soon as we find a way to fix it. @guillem-palau-salva is helping.

**Comment by aalemayhu** [comment]
Great work @alpkaanaksu! Thanks for helping out @guillem-palau-salva  🙏🏾 

https://youtu.be/bg1lZYKpj3E
