### ISSUE TITLE
[BUG] Page doesn’t render under Firefox

### ISSUE THREAD

**Issue by andrewcrook** [alemayhu/notion2anki#2]
I just get a blank page on the following setup

macOS 10.15.4
Firefox 75.0 (64bit)
MacBook Pro 13" 2019 i7 16Gb 

however, I can confirm Safari is working.

**Comment by scanf** [comment]
Hei @andrewcrook, I think this was due to the assumption I had that every card included an image.  I think this should be fixed, please reopen or let me know if that is not the case.

Thank you.
