### ISSUE TITLE
[Road map suggestion] Develop as a command line tool or Anki Plugin?

### ISSUE THREAD

**Issue by andrewcrook** [alemayhu/notion2anki#210]
I am not sure if the web is the way to go In the future. 
I think it should be completely local as a command line tool or, even better, as a plugin for Anki itself by adding an Import dialog option  "Notion (HTML) .ZIP ".

**Comment by aalemayhu** [comment]
I appreciate your feedback here but I am personally not interested in maintaining a command line tool or Anki add-on. I am very confident that the web is the way to go, let me elaborate.

I have worked in the Linux Networking space before and very familiar with the process of building CLI tools and to be honest it really sucks in so many ways. It's not an experience I desire for myself. Making websites is simple, rewarding, and normal people will appreciate it in many cases. The barrier for entry is lower. The tools are really good and they keep getting better.

It's no secret that add-on development for Anki is like the wild wild west. Stuff keeps breaking between versions and so on. Checkout this podcast episode for a better understanding of my views on this particular subject [Deep Weeb Podcast # 4 - Alexander Alemayhu and the challenges of the Anki Ecosystem](https://youtu.be/qJ740mmi8kE).

When all of that is said, if enough people beg me to create a official Anki add-on. I will likely do it, but until I am convinced of the return of investment it will only be a nice to have.

Please continue the discussion in #53 

Thanks!
