### ISSUE TITLE
[BUG] HTML code as Deck name

### ISSUE THREAD

**Issue by andrewcrook** [alemayhu/notion2anki#211]
I just imported a set of notes and noticed the Deck name in some screens shows as

`"deck:<svg viewBox=0 0 14 14 style=width:14px;height:14px;display:block;fill:rgba(55, 53, 47, 0.4);flex-shrink:0;-webkit-backface-visibility:hidden class=typesFile><path d=M5.94578,14 C4.62416,14 3.38248,13.4963 2.44892,12.585 C1.514641,11.6736 1,10.4639 1,9.17405 C1.00086108,7.88562 1.514641,6.67434 2.44892,5.76378 L7.45612,0.985988 C8.80142,-0.327216 11.1777,-0.332396 12.5354,0.992848 C13.9369,2.36163 13.9369,4.58722 12.5354,5.95418 L8.03046,10.2414 C7.16278,11.0877 5.73682,11.0894 4.86024,10.2345 C3.98394,9.37789 3.98394,7.98769 4.86024,7.1327 L6.60422,5.4317 L7.87576,6.67196 L6.13177,8.37297 C6.01668,8.48539 6.00003,8.61545 6.00003,8.68335 C6.00003,8.75083 6.01668,8.88103 6.13177,8.99429 C6.36197,9.21689 6.53749,9.21689 6.76768,8.99429 L11.2707,4.70622 C11.9645,4.03016 11.9645,2.91757 11.2638,2.23311 C10.5843,1.57007 9.40045,1.57007 8.72077,2.23311 L3.71342,7.0109 C3.12602,7.58406 2.79837,8.35435 2.79837,9.17405 C2.79837,9.99459 3.12602,10.7654 3.72045,11.3446 C4.90947,12.5062 6.98195,12.5062 8.17096,1`

Unfortunately, I cannot attach the notes but happy to send to the developer.

**Comment by aalemayhu** [comment]
Hei Andrew! I hope you are doing well. On the first glance, I think this seems to be from us embedding the page icons from Notion. Are you by any chance using a custom image in this page? If that's the case then disabling it in this case should resolve the issue.

**Comment by andrewcrook** [comment]
I have rendered the SVG and get

<img width="38" alt="image" src="https://user-images.githubusercontent.com/803618/97780910-920c2c80-1b7f-11eb-9cc1-3d9427e4e747.png">

the only place I can see this being used in Notion is 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/803618/97780931-b831cc80-1b7f-11eb-95b0-de7467b34f98.png">

looking at the rendered HTML export from Notion

<img width="372" alt="image" src="https://user-images.githubusercontent.com/803618/97780971-08109380-1b80-11eb-8488-a8239ba90ce1.png">

It looks like Notion is including these in the export I don't know if this is intended or a bug.
Perhaps Notion2Anki should strip this code out when converting?

**Comment by aalemayhu** [comment]
I will take a look at this next week, thanks!

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
Twitch: http://twitch.tv/alemayhu <http://twitch.tv/alemayhu>

**Comment by aalemayhu** [comment]
Hei @andrewcrook! I was not able to reproduce but for now I have added a new option for deck options which you can use to disable the deck description altogether. It will come out in the next deployment to production.

Thanks!

**Comment by aalemayhu** [comment]
I thought I had fixed this for all cases, but found another one today with CSV files. Will be fixed in the next deployment.
