### ISSUE TITLE
Preserve colours from Notion

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#29]
- Text color, background

Suggested-by: vd on Discord

> (2) It would be really cool to see background color added to the Anki cards, if there is background color that corresponds to the colored Notion Toggle Sections.

**Comment by scanf** [comment]
Supported.

**Comment by scanf** [comment]
This unfortunately breaks some styles so re-opening this until we have a better approach.

Related-to: #47

**Comment by aalemayhu** [comment]
So just for future me: Setting the background and then creating a toggle list inside it gives you the below. We should perserve the red tint in this case.

<img width="830" alt="Screenshot 2020-11-10 at 2 12 07 PM" src="https://user-images.githubusercontent.com/925044/98678379-bf669080-235e-11eb-9405-22d422bbc7ba.png">

**Comment by aalemayhu** [comment]
Reopening after triage: Preserving Notion text/background colours on cards is a real recurring UX ask; partial annotation support exists but toggle background colours still drop.. Reviewed by: designer agent.

**Comment by aalemayhu** [comment]
Closing — already implemented. Notion colors preserved via `NotionColors.ts` and `styleWithColors()` applied across block renderers.
