### ISSUE TITLE
Treat subpages export as multiple decks

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#4]
If subpages are detected should we ask user if they want to create multiple decks?

**Comment by scanf** [comment]
From Discord
> abiToday at 8:21 AM
:thumbsup:
I see you asked about nested pages earlier. Have you decided on them ? I thought I'll drop by an idea I had - we can make nested pages into a separate deck, and change the name of deck to indicate it's location in the toggles, so we know the flow n where that deck fits in. 
Ex - Say outside page is ABC n inside page DEF - change name to ABC --> DEF.

**Comment by scanf** [comment]
In the case where multiple HTML files are detected we could send the user to a new page that lists them out and streams them to the browser from the temp directory. This can also serve as a cache and prevent triggering too much load on the server.

**Comment by scanf** [comment]
This will be tackled next after the pending bugs are resolved.

**Comment by aalemayhu** [comment]
We will adress hopefully this week.

**Comment by aalemayhu** [comment]
While the implementation is mostly there, we need to test this some more and fix regressions. So moving it into next week.

**Comment by aalemayhu** [comment]
This got finally deployed, so happy!
