### ISSUE TITLE
Support sub-bullets and sub-numerations

### ISSUE THREAD

**Issue by henrik-de** [alemayhu/notion2anki#40]
Currently, everything is left-aligned + enumerations don't continue with the right number if there is a sub-bullet after the previous one

**Comment by scanf** [comment]
Can you provide an example file? Need to confirm if it's HTML or Markdown. Screenshot is also nice.

Which address did you use to upload? There are currently multiple versions of this project floating around 🙂

**Comment by henrik-de** [comment]
See screenshots below :)

![image](https://user-images.githubusercontent.com/66316518/87595688-38c2df00-c6ef-11ea-9ece-8c136452f2a5.png)
![image](https://user-images.githubusercontent.com/66316518/87595707-424c4700-c6ef-11ea-9b95-b545c3caaa8e.png)


Do you mean address as in this? https://notion2anki.alemayhu.com/upload.html

**Comment by scanf** [comment]
Yes we have multiple servers so I need to make sure I reproduce the issue with the right one. I will use the screenshot but please next time just send the same file you used for the uploading. It will save me sometime and the bugs will be fixed faster 😉 

Thanks.
