### ISSUE TITLE
Toggle "head line" displayed both on front AND back

### ISSUE THREAD

**Issue by henrik-de** [alemayhu/notion2anki#42]
See screenshots below:

![image](https://user-images.githubusercontent.com/66316518/87853597-b5320980-c90b-11ea-8f29-8efa079ee7ce.png)

![image](https://user-images.githubusercontent.com/66316518/87853579-9df31c00-c90b-11ea-8f0e-f4881c8cd290.png)

**Comment by scanf** [comment]
Thanks for reporting. I will take a look when I get a chance.

Mit freundlichen Grüßen

Alexander Alemayhu

**Comment by scanf** [comment]
Was this with the HTML or Markdown format?

**Comment by henrik-de** [comment]
This was HTML. Works for Markdown.

**Comment by scanf** [comment]
From Discord
> For example the "toggle header on the back of the card (not just the front)" happens when using HTML but not when using Markdown. But then again, sub-bullets don't work with Markdown but only with HTML.

**Comment by scanf** [comment]
This has been fixed, thanks.
