### ISSUE TITLE
Improve default notion style for iOS

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#52]
From Discord

> Quick newbie question: on Anki for desktop, all my cards are left-aligned as they should be but on my iPad they are centred. Do you guys know how I can change that globally? :grimacing:

## iOS

![image](https://user-images.githubusercontent.com/925044/88329409-32a1b380-cd2a-11ea-8d3a-46afafb8d94b.png)
## Desktop

![image](https://user-images.githubusercontent.com/925044/88329467-4b11ce00-cd2a-11ea-9941-dd8d959d0b32.png)

**Comment by scanf** [comment]
Will use this page to debug this issue https://www.notion.so/Anki-Conversion-Marketing-db5ea127a1024b46a4a9116dad013b1d

**Comment by scanf** [comment]
I suspect it's probably related to same media queries not being applied because of the viewport.

**Comment by scanf** [comment]
Comparing iPad Pro with a Samsung device, looks like Ankidroid has better defaults. Will take a look at the code upstream and see how they are doing it.

**Comment by aalemayhu** [comment]
We have some sane defaults now, thanks to Alp.
