### ISSUE TITLE
Update website to include slot for sponsor

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#75]
The basic idea is that anyone can become a sponsor if they can pay via Patreon. We need to clarify that on the site and explain what they are getting similiar to what Gruber does [https://daringfireball.net/feeds/sponsors/](https://daringfireball.net/feeds/sponsors/)

https://www.patreon.com/alemayhu

**Comment by scanf** [comment]
We have added a slot on the front page, maybe we should add more slots around the site. Like for example the upload page. What do you think @alpkaanaksu ?

**Comment by aalemayhu** [comment]
We have now covered this. Also the deck description includes a good enough info about the project. Thanks for the feedback @alpkaanaksu 🙏🏾
