### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by scanf** [alemayhu/notion2anki#9]
I have started redesigning the app and it would be nice to be able to invert the colours when using it late at night.

**Comment by scanf** [comment]
While nice, we have more important things to implement. This can be revisited next year.

**Comment by aalemayhu** [comment]
Reopening after triage: Dark mode for the web app remains a real, recurring user request; no theme system found in web/src today.. Reviewed by: designer agent.

**Comment by aalemayhu** [comment]
Closing — already implemented. Dark mode with system preference detection in `ThemeSwitcher.tsx`, `useTheme.ts`, and `theme.ts`.
