### ISSUE TITLE
FAQ: add answer to `How to add images?`

### ISSUE THREAD

**Issue by scanf** [alemayhu/notion2anki#90]
Linking to the video about the maps should be enough to demonstrate it.

Related-to: alemayhu/notion2anki#89

**Comment by aalemayhu** [comment]
Second-pass review (pm): Unanswered question - user signal should not be lost

Evidence: comment_count=0

**Comment by aalemayhu** [comment]
Closing as part of stale-issue triage. This references the old notion2anki imba `faq-page` (`q-w-a` tag), which no longer exists in the rewritten 2anki/server codebase — FAQ/help content now lives in the in-app Docs (`web/src/pages/DocsPage/content/`) and the Answers pages. There is also no demo-video asset available to link. Re-open with (a) the target surface (a specific Docs or Answers page) and (b) the video URL or image asset, and it's a quick add.
