### ISSUE TITLE
Make the video frames look a little bit nicer

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#93]
They currently do not look so good, would better use some kind of sane aspect ratio.

<img width="1174" alt="Skjermbilde 2020-08-10 kl  08 29 01" src="https://user-images.githubusercontent.com/925044/89756714-a215f200-dae3-11ea-8c5c-826e01549d36.png">

**Comment by scanf** [comment]
They might have already been fixed but let's take a closer. Especially on mobile screens.

**Comment by aalemayhu** [comment]
Still looks bad on mobile.

**Comment by aalemayhu** [comment]
Fixed in the next deployment on dev.
