### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 

### ISSUE THREAD

**Issue by scanf** [alemayhu/notion2anki#94]
Encoding issues for decks written in Norwegian.

[kosthold.zip](https://github.com/alemayhu/notion2anki/files/5057784/kosthold.zip)

**Comment by aalemayhu** [comment]
Second-pass review (engineer): Relevant code exists but no fix commit found

Evidence: code in: node_modules/.pnpm/esbuild@0.27.7/node_modules/esbuild/lib/main.d.ts
node_module

**Comment by aalemayhu** [comment]
Fixed in 2020 (commit d9032bbaf39d) by reading files as UTF-8; the current pipeline handles non-ASCII characters throughout extraction, serialization, and deck generation, with tests covering it. Closing as resolved — reopen with a sample file if you still hit a decode error.
