### ISSUE TITLE
Cloze hints

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/notion2anki#99]
Do we want to support hints on the cloze deletions currently they are being rendered as `[...]`. Which works fine for me but there is room for ambiguity in certain cases.

**Comment by guillem-palau-salva** [comment]
The syntax is easy: just a second double colon after the cloze content. For example:
`Kaleida was funded to the tune of $40 million by {{c1::Apple and IBM::companies}} in {{c2::1991::year}}`

So in Notion we can use the same convention:
Kaleida was funded to the tune of $40 million by `Apple and IBM::companies` in `1991::year`

**Comment by aalemayhu** [comment]
Too complicated. I want a simpler approach for people.

**Comment by aalemayhu** [comment]
This emoji ℹ️ could work well. I will try it out next week and see.

**Comment by aalemayhu** [comment]
As mentioned on Discord you can already set the hint by appending the colons. So this already works, but it would be nice to have an even simpler way to set it. In the future we might expose a different UI for creating cloze deletions.

**Comment by aalemayhu** [comment]
Reopening after triage: Cloze hints support is a real product feature on the core conversion path; still in scope.. Reviewed by: pm agent.

**Comment by aalemayhu** [comment]
Cloze hints already work via the `answer::hint` convention — appending `::your hint` after the answer inside a code-formatted cloze renders the hint in place of `[...]`. This is now documented on the Card types docs page in #3041. Closing per the document-and-close decision.
